# Generated by Django 3.1.5 on 2021-01-17 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_mailtrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtrack',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailtracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
